Attempt to fix serialization error when saving a progress note
	As per report from Marc there are circumstances which
	provoke a serialization error (40001) which is reported
	like this:

		TransactionRollbackError: could not serialize access due to read/write dependencies among transactions
		DETAIL:  Reason code: Canceled on conflict out to pivot 405717, during read.
		HINT:  The transaction might succeed if retried.

	The code in which this happens opens a rw connection and
	sends a number of SELECT/INSERT/SELECT sequences for
	inserting individual rows into clin.clin_narrative. The
	INSERT effects a trigger to be run for creating a table
	modification NOTIFY which, in turn, runs a SELECT against
	clin.clin_narrative retrieving the NOTIFY payload. My
	best guess is that said SELECT acts as a pivot and leads
	to a rw dependency later if other INSERTS follow the
	first one even though the NOTIFY isn't actually _sent_
	before the whole transaction commits, the problem being
	that the payload of the queued-but-not-yet-sent NOTIFY
	contains data which may well have changed by an INSERT
	happening after the SELECT for the payload.

	Try to fix by marking the notification triggers not only
	DEFERRABLE but also INITIALLY DEFERRED such that the
	payload SELECT(s) are only run at commit time which
	cannot conflict with any INSERTs within the same TX
	anymore.

	Thanks $DEITY we went anally rententive with such matters
	right from day one and used transaction isolation mode
	SERIALIZABLE (SSI).