Fix exception when logging attributes
	Sometimes, attributes can't be logged, despite supposedly
	existing by showing up in __dict__. Log that fact instead.

		2020-12-03 14:38:28  ERROR     gm.gui        [3082374272 MainThread]  (/usr/share/gnumed/Gnumed/wxpython/gmExceptionHandlingWidgets.py::mail_log() #450): cannot send bug report
		Traceback (most recent call last):
		  File "/usr/share/gnumed/Gnumed/pycommon/gmNetworkTools.py", line 447, in send_email
		    refused = session.sendmail(sender, receiver, email.as_string())
		  File "/usr/lib/python3.8/smtplib.py", line 885, in sendmail
		    raise SMTPRecipientsRefused(senderrs)
		smtplib.SMTPRecipientsRefused: {}

		During handling of the above exception, another exception occurred:

		Traceback (most recent call last):
		  File "/usr/share/gnumed/Gnumed/wxpython/gmExceptionHandlingWidgets.py", line 438, in mail_log
		    gmNetworkTools.compose_and_send_email (
		  File "/usr/share/gnumed/Gnumed/pycommon/gmNetworkTools.py", line 471, in compose_and_send_email
		    return send_email (
		  File "/usr/share/gnumed/Gnumed/pycommon/gmNetworkTools.py", line 452, in send_email
		    gmLog2.log_stack_trace()
		  File "/usr/share/gnumed/Gnumed/pycommon/gmLog2.py", line 170, in log_stack_trace
		    logger.debug('  %s: %s', attr, getattr(v, attr))
		AttributeError: characters_written

(cherry picked from commit acb7e054fafb67ad56f9b0c6719e4f2aaeb462c2)